/*
 * FATHOM — global configuration & tuning constants.
 *
 * This is the first script loaded. It establishes the global `FATHOM` namespace
 * that every other module attaches to. We use plain (non-module) scripts sharing
 * one namespace so the game runs directly from `file://` with no build step and
 * no local server — double-click index.html and it plays.
 *
 * All gameplay numbers live here so the whole feel of the game can be tuned in
 * one place. The design doc (docs/GAME_DESIGN.md) explains the "why" behind the
 * core double-bind: you must PING to see, but the creature hears every ping.
 */
(function (F) {
  'use strict';

  // Fixed internal render resolution. The canvas is scaled to fit the window
  // while preserving this aspect ratio, so the game looks identical everywhere.
  F.VIEW = { w: 960, h: 600 };

  // World is a grid of square tiles. One tile == TILE pixels.
  F.TILE = 48;

  F.CONFIG = {
    // ---- Fixed-timestep simulation ----
    fixedDt: 1 / 120,        // seconds per simulation step
    maxFrameDt: 0.25,        // clamp huge frame gaps (tab unfocus) to avoid spiral-of-death

    // ---- Player ----
    player: {
      radius: 11,            // px, collision radius
      accel: 1400,           // px/s^2 toward desired velocity
      maxSpeed: 150,         // px/s normal swim
      quietSpeedMult: 0.42,  // hold to swim silently but slow
      drag: 6.5,             // velocity damping per second (water)
      // Noise (in "loudness" units, 0..1+) generated by the player.
      swimNoise: 0.34,       // continuous noise while swimming at full speed
      quietSwimNoise: 0.20,  // continuous noise while swimming quietly (must clear
                             // the entity's 0.05 audible floor so quiet-swim still
                             // makes a small, real bubble — not perfect silence)
      bumpNoise: 0.65,       // impulse noise when colliding into a wall hard
      bumpSpeedThreshold: 70 // min speed into a wall to count as a "bump"
    },

    // ---- Sonar ping (the core verb) ----
    ping: {
      speed: 540,            // px/s the ring expands
      maxRadius: 980,        // px, how far a ping travels before dying
      cooldown: 0.85,        // s between pings
      width: 26,             // px, thickness of the active ring band that "paints" surfaces
      noise: 1.0,            // loudness of a ping (the loudest thing you can do)
      revealFade: 2.6,       // s for a painted surface to fade back to black
      // A short, very dim self-glow so you are never 100% blind (fairness) — but
      // kept just over one tile (48px) so you cannot navigate the maze on the glow
      // alone: you must ping to find your way, which is the whole point.
      passiveVision: 58,     // px radius of faint always-on reveal around the player
      // Pings cost a small bit of breath (so spamming also drains you).
      oxygenCost: 1.0
    },

    // ---- Oxygen (the second bind) ----
    oxygen: {
      start: 80,             // s of air at depth 1
      drainPerSec: 1.0,      // base drain
      gaspNoise: 0.8,        // loud gasp when you refill at an air pocket
      refillRate: 34,        // air-seconds restored per real second at a pocket
      lowThreshold: 18,      // s remaining where the heartbeat/redout kicks in
      criticalThreshold: 7,  // s remaining where vision starts to gray/blur (drowning)
      // Fear spiral: being near the Angler makes you breathe faster, draining air
      // up to this multiplier at point-blank — panic literally suffocates you.
      // (Applied against sqrt(threat) so it bites at mid-range, not only on contact.)
      fearDrainMult: 2.4,
      // Involuntary drowning: at 0 air you do not die instantly. You thrash and
      // gasp (loud!) for this long — a slim chance to reach air, but you hand the
      // creature your exact position.
      drownWindow: 2.5
    },

    // ---- The entity ("the Angler") ----
    entity: {
      radius: 16,
      baseSpeed: 92,         // px/s while actively hunting (depth 1)
      patrolSpeed: 46,       // px/s while wandering with no target
      // How far different noises carry to the entity (px). Pings are heard almost
      // anywhere; quiet swimming barely carries (but its floored range must exceed
      // killRadius, or silent crawling becomes literally undetectable).
      hearPing: 1500,
      hearSwim: 520,
      hearBump: 520,
      hearGasp: 900,
      killRadius: 22,        // px, contact distance that triggers death
      // After hearing a noise it commits to that point; it loses interest after
      // this long with no new noise and returns to patrol.
      interestSec: 6.5,
      // Re-acquire cadence: it can only "lock" a new sound this often (prevents
      // it from being a perfect tracker — gives the player escape windows).
      relockSec: 0.6,
      // Proximity at which the heartbeat + distortion begin (px).
      dreadRadius: 300,
      // Chance, when a ping reveals the entity within `faceRadius`, of the rare
      // full-screen "face" reveal flourish.
      faceRadius: 150,
      faceScareChance: 0.5   // only rolls when already very close, so still rare
    },

    // ---- World generation ----
    world: {
      baseCols: 23,          // tiles (odd numbers carve cleaner mazes)
      baseRows: 23,
      growthPerDepth: 2,     // maze grows with depth
      maxCols: 41,
      maxRows: 41,
      beaconsBase: 3,        // collect this many to open the descent at depth 1
      beaconsPerDepth: 1,
      airPocketsBase: 5,
      // The world is an OPEN, looping wreck — not a thin maze. Heavy braiding
      // removes almost every dead-end so there is always a way around the Angler,
      // and open rooms give you space to dodge it. This is the key to never being
      // "cornered on the only path".
      braidChance: 0.85,     // fraction of dead-ends opened into loops
      roomsBase: 5,          // open chambers carved into the structure
      roomsPerDepth: 0.5,
      roomMinSize: 2,
      roomMaxSize: 4,
      startRoom: 3           // size of the open starting chamber
    },

    // ---- Scoring ----
    score: {
      perBeacon: 250,
      perDepth: 1000,
      airBonusPerSecAtDescent: 6, // remaining air banked when you descend
      timeBonusGrace: 45,         // seconds per depth before a small time penalty applies
      // Style multiplier: nerve pays. It climbs the longer you go without pinging
      // (navigating blind from memory) and drops when you ping. Multiplies beacon
      // and depth score.
      styleGain: 0.05,            // +mult per second of not pinging
      styleMax: 3.0,
      styleOnPing: 0.55           // multiplier retained after a ping (the rest is lost)
    }
  };

  // Difficulty scaling applied per depth. `progression.js` computes the live
  // values; these are the curve parameters.
  F.SCALING = {
    entitySpeedPerDepth: 6.0,   // +px/s hunting speed each depth
    entitySpeedMax: 168,
    oxygenLossPerDepth: 3.0,    // start air shrinks each depth
    oxygenMinStart: 42,
    extraEntityEveryDepths: 4,  // a second/third Angler appears this often
    maxEntities: 3,
    darknessPerDepth: 0.055,    // passive vision shrinks with depth (multiplier)
    minPassiveVisionMult: 0.5,
    hearGrowthPerDepth: 0.05,   // the Angler's ears sharpen +5%/depth (cap below)
    hearGrowthMax: 1.6          // up to +60% hearing range at depth
  };

  // Visual identity.
  F.PALETTE = {
    bg: '#000000',
    sonar: '#7fe9ff',        // cold cyan reveal
    sonarDim: '#2a4d57',
    wall: '#9fd8e6',
    bone: '#d7e3ea',
    blood: '#ff3b3b',
    beacon: '#ffd166',       // warm gold — the thing you want
    air: '#7CFFB2',          // green air pockets
    entity: '#ff3b3b'
  };

  // Single source of truth for the "danger" colour (creature, low-oxygen, dread
  // vignette). Returns an "r,g,b" string; the colorblind-safe variant shifts off
  // pure red toward a high-contrast amber so red/green-deficient players can read it.
  F.dangerRGB = function (settings) {
    return (settings && settings.colorblindSafe) ? '255,150,0' : '255,45,55';
  };

  // Default, persisted settings (see core/storage.js).
  F.DEFAULT_SETTINGS = {
    masterVolume: 0.85,
    sfxVolume: 1.0,
    musicVolume: 0.7,
    reducedFlashing: false,   // photosensitivity: damp white flashes & face reveal
    screenShake: 1.0,         // 0..1 multiplier
    subtitles: true,          // text cues for important audio (accessibility)
    colorblindSafe: false,    // shift danger color off pure red toward high-contrast amber
    invertQuiet: false,       // hold-to-go-fast instead of hold-to-go-quiet
    showFps: false
  };

  F.VERSION = '1.0.0';
})(window.FATHOM = window.FATHOM || {});
